### ISSUE TITLE
How the FloatMathPlugin works?

### ISSUE THREAD

**Issue by zwang** [johnmci/Scratch.app.for.iOS#2]
Hi @johnmci 

I am trying to integrate FDLIBM library into my Swift based (with some objc and c code too) iOS app. However, some of methods there are conflicting with math.h which is automatically included in iOS. I searched online and found your project does this. I am trying to understand how the FloatMathPlugin works so I can integrate into my app. Right now as long as I added the source code to the project, it will cause compiler issue saying redundant declaration etc. 

Also, In my app, I need to use `cos`, `sin` these methods already existing in `math.h`. Is that possible doing?

I will really appreciate it if you can give me some insights of your solution, maybe advice/tips about how I can make it work for my case too. Thank you very much for reading this. Have a wonderful day!

**Comment by johnmci** [comment]
Ok, well the Smalltalk Squeak VM builds an external library called
FloatMath.plugin which wraps each transcendental call, say __ieee754_cos so
that when the Smalltalk virtual machine call the primitive we load the
plugin, then jump to the primitive api, where we unbox the ieee floating
point value, place it into a float then call  __ieee754_cos with the value.
The results are then reboxed and the smalltalk object returned to the
caller.

If you look at the source code in the FloatMathPlugin you'll see we added
the following "ieee754names.h" so that FDLIBM cos always is __ieee754_cos and
doesn't collide with math.h cos()

/\* Re-define all of the conflicting names of fdlibm to use __ieee754_
prefix */

#define asinh __ieee754_asinh

#define atan __ieee754_atan

#define cos __ieee754_cos

#define expm1 __ieee754_expm1

#define finite __ieee754_finite

#define ldexp __ieee754_ldexp

#define scalbn __ieee754_scalbn

#define log1p __ieee754_log1p

#define modf __ieee754_modf

#define rint __ieee754_rint

#define sin __ieee754_sin

#define tan __ieee754_tan

#define tanh __ieee754_tanh

We compile cos.c which is

#include "ieee754names.h"

#include "fdlibm/s_cos.c"

On Wed, Feb 24, 2016 at 10:34 AM, Zhao Wang notifications@github.com
wrote:

> Hi @johnmci https://github.com/johnmci
> 
> I am trying to integrate FDLIBM library into my Swift based (with some
> objc and c code too) iOS app. However, some of methods there are
> conflicting with math.h which is automatically included in iOS. I searched
> online and found your project does this. I am trying to understand how the
> FloatMathPlugin works so I can integrate into my app. Right now as long as
> I added the source code to the project, it will cause compiler issue saying
> redundant declaration etc.
> 
> Also, In my app, I need to use cos, sin these methods already existing in
> math.h. Is that possible doing?
> 
> I will really appreciate it if you can give me some insights of your
> solution, maybe advice/tips about how I can make it work for my case too.
> Thank you very much for reading this. Have a wonderful day!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/johnmci/Scratch.app.for.iOS/issues/2.

## 

# 

John M. McIntosh. Corporate Smalltalk Consulting Ltd

# https://www.linkedin.com/in/smalltalk

**Comment by zwang** [comment]
@johnmci  thanks a lot for the explanation. It makes sense now. Appreciate your help. Have a great day! :+1:
